services:
  task-organize:
    build: .
    expose:
      - 5000
    volumes:
      - uploads:/app/static/uploads
      - data:/app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  uploads:
  data:
